# Generated by Django 5.0.1 on 2024-01-13 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee_info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=100)),
                ('leave_type', models.CharField(choices=[('Casual Leave', 'Casual Leave'), ('Sick Leave', 'Sick Leave'), ('Earned Leave', 'Earned Leave'), ('Adjusted Leave', 'Adjusted Leave'), ('Half-day Leave', 'Half-day Leave'), ('Unpaid Leave', 'Unpaid Leave')], max_length=100)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee_info.employee')),
            ],
        ),
    ]
